# Generated by Django 5.1.2 on 2024-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
