# Generated by Django 5.1.2 on 2024-12-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_alter_departmentmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentmodel', unique=True)),
            ],
        ),
    ]
