# Generated by Django 5.1.2 on 2024-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_dashboard', '0002_staffmodel_year_alter_staffmodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='joined_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
